-- GENERATED by supabase/seed/generate-seed.ts — do not edit by hand.
-- Source of truth is the Phase 1 mock data in src/data/. Regenerate with:
--   npx tsx supabase/seed/generate-seed.ts

-- Content: theme islands

insert into english_themes (id, title, can_do, sort_order, emoji) values
  ('weather', 'Weather', 'I can name the weather.', 0, '⛅'),
  ('animals', 'Animals', 'I can name farm and wild animals.', 1, '🦁'),
  ('food', 'Food', 'I can name food I like.', 2, '🍎'),
  ('colors', 'Colors', 'I can name the colors.', 3, '🌈')
on conflict (id) do update set title = excluded.title, can_do = excluded.can_do, sort_order = excluded.sort_order, emoji = excluded.emoji;

-- Content: vocabulary items

insert into english_items (id, theme_id, word, emoji, vi, min_level, sort_order) values
  ('weather-sunny', 'weather', 'sunny', '☀️', 'nắng', 'starter', 0),
  ('weather-rainy', 'weather', 'rainy', '🌧️', 'mưa', 'starter', 1),
  ('weather-cloudy', 'weather', 'cloudy', '☁️', 'nhiều mây', 'starter', 2),
  ('weather-windy', 'weather', 'windy', '🌬️', 'gió', 'starter', 3),
  ('weather-hot', 'weather', 'hot', '🥵', 'nóng', 'starter', 4),
  ('weather-cold', 'weather', 'cold', '🥶', 'lạnh', 'starter', 5),
  ('weather-snowy', 'weather', 'snowy', '❄️', 'tuyết', 'mover', 6),
  ('weather-stormy', 'weather', 'stormy', '⛈️', 'bão', 'mover', 7),
  ('weather-foggy', 'weather', 'foggy', '🌫️', 'sương mù', 'mover', 8),
  ('animals-cat', 'animals', 'cat', '🐱', 'mèo', 'starter', 0),
  ('animals-dog', 'animals', 'dog', '🐶', 'chó', 'starter', 1),
  ('animals-bird', 'animals', 'bird', '🐦', 'chim', 'starter', 2),
  ('animals-fish', 'animals', 'fish', '🐟', 'cá', 'starter', 3),
  ('animals-frog', 'animals', 'frog', '🐸', 'ếch', 'starter', 4),
  ('animals-duck', 'animals', 'duck', '🦆', 'vịt', 'starter', 5),
  ('animals-lion', 'animals', 'lion', '🦁', 'sư tử', 'mover', 6),
  ('animals-tiger', 'animals', 'tiger', '🐯', 'hổ', 'mover', 7),
  ('animals-monkey', 'animals', 'monkey', '🐵', 'khỉ', 'mover', 8),
  ('animals-bear', 'animals', 'bear', '🐻', 'gấu', 'mover', 9),
  ('animals-horse', 'animals', 'horse', '🐴', 'ngựa', 'mover', 10)
on conflict (id) do update set theme_id = excluded.theme_id, word = excluded.word, emoji = excluded.emoji, vi = excluded.vi, min_level = excluded.min_level, sort_order = excluded.sort_order;

-- Content: skill huts

insert into huts (id, theme_id, skill) values
  ('weather-listen', 'weather', 'listen'),
  ('weather-speak', 'weather', 'speak'),
  ('weather-read', 'weather', 'read'),
  ('weather-write', 'weather', 'write'),
  ('animals-listen', 'animals', 'listen'),
  ('animals-speak', 'animals', 'speak'),
  ('animals-read', 'animals', 'read'),
  ('animals-write', 'animals', 'write'),
  ('food-listen', 'food', 'listen'),
  ('food-speak', 'food', 'speak'),
  ('food-read', 'food', 'read'),
  ('food-write', 'food', 'write'),
  ('colors-listen', 'colors', 'listen'),
  ('colors-speak', 'colors', 'speak'),
  ('colors-read', 'colors', 'read'),
  ('colors-write', 'colors', 'write')
on conflict (id) do update set theme_id = excluded.theme_id, skill = excluded.skill;

-- Content: sticker catalog

insert into stickers (id, name, emoji, "set", rarity, tags) values
  ('boy-captain-comet', 'Captain Comet', '🦸', 'boy', 'legendary', ARRAY['hero', 'space']::text[]),
  ('boy-emberon-dragon', 'Emberon', '🐉', 'boy', 'legendary', ARRAY['dragon', 'fantasy']::text[]),
  ('boy-bolt-9', 'Bolt-9', '🤖', 'boy', 'epic', ARRAY['robot', 'machine']::text[]),
  ('boy-rex-thunder', 'Rex Thunder', '🦖', 'boy', 'epic', ARRAY['dino']::text[]),
  ('boy-shadow-ninja', 'Shadow', '🥷', 'boy', 'epic', ARRAY['ninja']::text[]),
  ('boy-astro-sam', 'Astro Sam', '👨‍🚀', 'boy', 'epic', ARRAY['space']::text[]),
  ('boy-merlin-jr', 'Merlin Jr.', '🧙', 'boy', 'epic', ARRAY['wizard', 'fantasy']::text[]),
  ('boy-turbo-dash', 'Turbo Dash', '🏎️', 'boy', 'rare', ARRAY['vehicle', 'speed']::text[]),
  ('boy-blaze-rocket', 'Blaze', '🚀', 'boy', 'rare', ARRAY['space', 'vehicle']::text[]),
  ('boy-sir-brave', 'Sir Brave', '🛡️', 'boy', 'rare', ARRAY['knight']::text[]),
  ('boy-sparky-bot', 'Sparky', '⚡', 'boy', 'rare', ARRAY['robot', 'energy']::text[]),
  ('boy-zax-alien', 'Zax', '👽', 'boy', 'rare', ARRAY['alien', 'space']::text[]),
  ('boy-sky-eagle', 'Sky', '🦅', 'boy', 'rare', ARRAY['animal', 'bird']::text[]),
  ('boy-kong-mighty', 'Kong', '🦍', 'boy', 'rare', ARRAY['animal']::text[]),
  ('boy-webster-spider', 'Webster', '🕷️', 'boy', 'rare', ARRAY['animal', 'bug']::text[]),
  ('boy-captain-octo', 'Captain Octo', '🐙', 'boy', 'rare', ARRAY['sea']::text[]),
  ('boy-moby-whale', 'Moby', '🐋', 'boy', 'rare', ARRAY['sea']::text[]),
  ('boy-finn-shark', 'Finn', '🦈', 'boy', 'common', ARRAY['sea', 'animal']::text[]),
  ('boy-leo-roar', 'Leo', '🦁', 'boy', 'common', ARRAY['animal']::text[]),
  ('boy-tiger-bolt', 'Tiger', '🐯', 'boy', 'common', ARRAY['animal']::text[]),
  ('boy-rusty-fox', 'Rusty', '🦊', 'boy', 'common', ARRAY['animal']::text[]),
  ('boy-barnaby-bear', 'Barnaby', '🐻', 'boy', 'common', ARRAY['animal']::text[]),
  ('boy-hopper-frog', 'Hopper', '🐸', 'boy', 'common', ARRAY['animal']::text[]),
  ('boy-slither-snake', 'Slither', '🐍', 'boy', 'common', ARRAY['animal']::text[]),
  ('boy-snappy-crab', 'Snappy', '🦀', 'boy', 'common', ARRAY['sea']::text[]),
  ('boy-max-truck', 'Max', '🚜', 'boy', 'common', ARRAY['vehicle']::text[]),
  ('boy-kick-striker', 'Striker', '⚽', 'boy', 'common', ARRAY['sports']::text[]),
  ('boy-ollie-skater', 'Ollie', '🛹', 'boy', 'common', ARRAY['sports']::text[]),
  ('boy-croc-drake', 'Drake', '🐊', 'boy', 'common', ARRAY['animal']::text[]),
  ('boy-dash-dog', 'Dash', '🐶', 'boy', 'common', ARRAY['animal', 'pet']::text[]),
  ('girl-princess-lumi', 'Princess Lumi', '👸', 'girl', 'legendary', ARRAY['royalty']::text[]),
  ('girl-stella-unicorn', 'Stella', '🦄', 'girl', 'legendary', ARRAY['unicorn', 'fantasy']::text[]),
  ('girl-faye-fairy', 'Faye', '🧚', 'girl', 'epic', ARRAY['fairy', 'magic']::text[]),
  ('girl-marina-mermaid', 'Marina', '🧜‍♀️', 'girl', 'epic', ARRAY['mermaid', 'sea']::text[]),
  ('girl-queen-petal', 'Queen Petal', '🌸', 'girl', 'epic', ARRAY['royalty', 'flower']::text[]),
  ('girl-luna-moon', 'Luna', '🌙', 'girl', 'epic', ARRAY['celestial', 'magic']::text[]),
  ('girl-wanda-wand', 'Wanda', '🪄', 'girl', 'rare', ARRAY['magic']::text[]),
  ('girl-rosie-rainbow', 'Rosie', '🌈', 'girl', 'rare', ARRAY['nature', 'color']::text[]),
  ('girl-swan-grace', 'Grace', '🦢', 'girl', 'rare', ARRAY['animal', 'bird']::text[]),
  ('girl-della-dolphin', 'Della', '🐬', 'girl', 'rare', ARRAY['sea']::text[]),
  ('girl-mimi-bird', 'Mimi', '🐦', 'girl', 'rare', ARRAY['animal', 'bird']::text[]),
  ('girl-sparkle-heart', 'Sparkle', '💖', 'girl', 'rare', ARRAY['magic', 'love']::text[]),
  ('girl-bella-butterfly', 'Bella', '🦋', 'girl', 'common', ARRAY['nature', 'bug']::text[]),
  ('girl-kiki-kitten', 'Kiki', '🐱', 'girl', 'common', ARRAY['animal', 'pet']::text[]),
  ('girl-twinkle-star', 'Twinkle', '⭐', 'girl', 'common', ARRAY['celestial']::text[]),
  ('girl-coco-cupcake', 'Coco', '🧁', 'girl', 'common', ARRAY['treat']::text[]),
  ('girl-daisy-deer', 'Daisy', '🦌', 'girl', 'common', ARRAY['animal']::text[]),
  ('girl-bonnie-bunny', 'Bonnie', '🐰', 'girl', 'common', ARRAY['animal', 'pet']::text[]),
  ('girl-penny-pony', 'Penny', '🐴', 'girl', 'common', ARRAY['animal']::text[]),
  ('girl-pia-panda', 'Pia', '🐼', 'girl', 'common', ARRAY['animal']::text[]),
  ('girl-blossom-tulip', 'Blossom', '🌷', 'girl', 'common', ARRAY['nature', 'flower']::text[]),
  ('girl-lila-ladybug', 'Lila', '🐞', 'girl', 'common', ARRAY['nature', 'bug']::text[]),
  ('girl-cleo-cloud', 'Cleo', '☁️', 'girl', 'common', ARRAY['sky']::text[]),
  ('girl-tilly-teacup', 'Tilly', '🫖', 'girl', 'common', ARRAY['treat']::text[]),
  ('girl-gigi-giraffe', 'Gigi', '🦒', 'girl', 'common', ARRAY['animal']::text[]),
  ('girl-ellie-elephant', 'Ellie', '🐘', 'girl', 'common', ARRAY['animal']::text[]),
  ('girl-honey-bee', 'Honey', '🐝', 'girl', 'common', ARRAY['nature', 'bug']::text[]),
  ('girl-polly-penguin', 'Polly', '🐧', 'girl', 'common', ARRAY['animal']::text[]),
  ('girl-hazel-hamster', 'Hazel', '🐹', 'girl', 'common', ARRAY['animal', 'pet']::text[]),
  ('girl-shelly-shell', 'Shelly', '🐚', 'girl', 'common', ARRAY['sea']::text[])
on conflict (id) do update set name = excluded.name, emoji = excluded.emoji, "set" = excluded."set", rarity = excluded.rarity, tags = excluded.tags;

-- Children (parent_id backfilled when auth lands in task 18)

insert into children (id, name, avatar, sticker_set) values
  ('milo', 'Milo', '🦊', 'boy'),
  ('sunny', 'Sunny', '🐰', 'girl')
on conflict (id) do update set name = excluded.name, avatar = excluded.avatar, sticker_set = excluded.sticker_set;

-- Per-skill levels

insert into child_skill_levels (child_id, skill, level) values
  ('milo', 'listen', 'starter'),
  ('milo', 'speak', 'starter'),
  ('milo', 'read', 'starter'),
  ('milo', 'write', 'starter'),
  ('sunny', 'listen', 'mover'),
  ('sunny', 'speak', 'mover'),
  ('sunny', 'read', 'mover'),
  ('sunny', 'write', 'starter')
on conflict (child_id, skill) do update set level = excluded.level;
